danmar/simplecpp

simplecpp.cpp, test.cpp
Although raw string literals are correctly parsed, their actual content is wrong: If I read the code in the simplecpp and cppcheck projects correctly, the intention is that the raw string literals are converted to normal string literals. To do this, one must escape special chars in the raw string literal, which is exactly what is done in this patch. Another approach would be keeping the raw string literals as they are, but I think cppcheck would need some changes then, too.
The fix needs to be pushed to cppcheck's copy, too, otherwise it gets the following code wrong:
```C++
static void bar(const char*) {}
static void baz(int) {}
int main() {
bar(R"(")");
baz(123);
bar(R"(")");
}
```
Without the patch, cppcheck incorrectly complains about `baz` being never used. I guess what's going on is …
=> Fixed quoting of raw string literals.

Makefile
This change allows usage of CXXFLAGS and LDFLAGS - so far at least in addition to the still hardcoded ones.
=> Allow usage of user-specific compiler and linker flags

.gitignore, simplecpp.cpp
Result on example from #46:
input.c:1: syntax error: failed to evaluate #if condition
With cppcheck:
Checking input.c ...
[./input.c:1]: (error) failed to evaluate #if condition
=> Fix #46, add Linux binary files to gitignore

Makefile
Files should only be compiled once. Use LDFLAGS where appropriate
=> Re-use object files

simplecpp.cpp, test.cpp
This PR fixes 2 issues:
1. `dir/../` wasn't simplified away when it was located at the path start. This lead to non-simplified paths in cppcheck report for errors in headers included like that: `#include "../foo.h"` First patch fixes that.
2. Only one instance of `./` was removed from the path start. Second patch fixes that.
There is also a case when `dir//../` would be incorrectly simplified to `dir/`. This could be fixed either by replacing all consecutive slashes with one slash everywhere or by starting search for a slash from the first non-slash before the matched `/../`. I think first solution would be much cleaner, what would you prefer?
=> Fix corner cases in simplifyPath()

simplecpp.cpp
This resolves https://github.com/danmar/simplecpp/issues/97
=> Ensure valueToken is assigned in Macro::parseDefine

simplecpp.cpp
All other such calls have a cast (most likely to avoid "return value not used" static analysis complaints). This line is as good as those other lines.
=> Cast result of istream::get() uniformly with surrounding code

simplecpp.cpp
by using the [faster ](https://ariccio.com/2015/01/13/how-fast-are-findfirstfilefindfirstfileex-and-cfilefind-actually/) FindFirstFileEx with `FindExInfoBasic` since not more is required at that spot.
Also return from `getFileName()` early if the haystack `filedata` is empty. The function is within the top 10 of CPU time consumers when running against a fairly large codebase and measuring with Visual Studio 2017 Performance Analysis.
Both improvements have led to an analysis time decrease of between 5% (solution with 14 projects, 3022 files to check) and 15% (solution with 645 projects, 21714 files to check).
=> Improve performance on windows

simplecpp.cpp
This adds a cache to the realFileName call to improve performance of check times on Windows. 
Prior to this change, cppcheck was taking 30 minutes to run on a codebase consisting of 87 solutions, 594 projects and 18000 files (using -j8). 
After this change, cppcheck now takes 12.7 minutes (-j8). 
We have been using cppcheck 1.85 with this change since October last year without issues in our nightly.
=> Cache results of FindFirstFileExA to improve performance on Windows

simplecpp.cpp, test.cpp
Previously, simplecpp would throw an error for invalid usage of ## for
the following code:
#define ADD_OPERATOR(OP) void operator OP ## = (void) { x = x OP 1; }
ADD_OPERATOR(+)
This commit allows the above macro work with all allowed c and c++
compound assignment operators.
Note that
#define A < ## < ## =
A
will still throw an error.
=> Fix ## of assignement operators. Fixes #141

simplecpp.cpp
Add a missing call to istream.unget() in case the file starts with 0xfe
or 0xff but does not continue with 0xff. This makes simplecpp abort
parsing immediately on such files, instead of silently ignoring the first
character and continue parsing.
Also, save return value of istream.peek() as int. If the file is empty,
istream.peek() returns EOF (a negative int value, typically -1).
It was silently converted to unsigned char, which made it take a
somewhat unintentional path before returning. Note that there was no
erroneous parsing, or undefined behaviour. Fixes #133.
=> Minor fixes to getAndSkipBOM()

simplecpp.cpp
2nd try (replacing 1st try #146):
This further improves "real file name" caching by letting the outer function realFilename(const std::string &f) access the same cache as the inner function realFileName(const std::string &f, std::string *result)
Cppcheck runtime with earlier PR #145 applied: 31 mins
Cppcheck runtime with both PRs applied: 13.7 mins (-55.8%)
Both using -j24 on my large solution (see PR #144).
@danmar In your review for PR #144 you stated:
> I should have been more worried about it before .. but I am not sure that this will work for relative paths. The path "foo/src.cpp" might be "Foo/Src.cpp" in one folder and "foo/srC.cpp" in another folder.
As I see it, getting the real case-sensitive file name (Windows only) for relative paths usually cannot succeed anyway …
=> Use realFileNameMap cache also in outer realFilename function

simplecpp.cpp
This PR fixes #151: Caches the file paths of all non-existing header files in a thread-safe set.
As agreed upon in #151, caching is enabled for Windows only.
Time measurements showed that caching the results of simplecpp::simplifyPath does not decrease checking time significantly, so I did not change anything in simplifyPath.
=> Cache non-existing header files to skip expensive file open call

simplecpp.cpp, simplecpp.h, test.cpp
Here are the fixes for the bugs discussed in #152:
- fix for loop condition in realFileName: scan also f[0]
- use separate caches for realFilename (realFilePathMap stores entire paths) and realFileName (realFileNameMap stores file names)
- convert Cygwin paths to Windows paths in call to FindFirstFileExA
- added testcase for convertCygwinToWindowsPath
I put convertCygwinToWindowsPath into namespace simplecpp to be able to access it from test.cpp.
=> 3 fixes for realFileName/realFilename

simplecpp.cpp, test.cpp
Previously, simplecpp would output the character `L'a'` as two tokens `"L"`
and `"'a'"`. A user of the tokens has no way of knowing if they were
originally `"L'a'"` och `"L 'a'"`.
=> Merge string and character literal with prefix

simplecpp.cpp, test.cpp
Commit 4e022f0a8d7c2a669260e1a0f93dc27d4bad702d broke parsing of
multiline prefixed strings in defines. The commit changed so all
prefixed strings went through the same code path that previously
only raw string literals did. That didn't handle newlines in
defines well. Change this to strip out the prefix first, and then
check if it is a raw string or not.
=> Fix multiline prefixed string literals in macros

simplecpp.cpp, test.cpp
Add error messages to ill formed raw string literals. There was a TODO
for adding an error message in case reading a string failed, (i.e., it
was not terminated properly. There was already an error message from
readUntil() so remove the TODO and add a few test cases.
=> Add error message to ill-formed string and character literals

test.cpp
Commit 4e022f0a8d7c2a669260e1a0f93dc27d4bad702d broke (among other
things), parsing of prefixed strings with \" and prefixed characters
containing \'. This (and other things) was fixed in
1eb30dcea852431f3e355383534ea527e48c0b5d. Add tests for this.
=> Add regression tests for string literals with " inside

simplecpp.cpp, test.cpp
The prevChar was broken in the sense that there is no guarantee that
unget can be called more than once on a stream. This lead to problems in
some cases on some operative systems. Fix this by saving the state
before reading the character. Note that prevIsSpace is not valid in the
entire while loop, if characters are read on other places than at the
start of the while loop, the value will be wrong. This is the case in
the only place that it is being used.
This feels like a very brittle solution...
=> Fix check if previous read character was space

simplecpp.cpp, simplecpp.h
gets rid of copy of result in Preprocessor::preprocess()
reduces Ir from 14.98% to 12.70% with package pion according to callgrind
=> added move constructor and assignment for TokenList

CMakeLists.txt, Makefile, test.cpp
also removed -Wabi since it will no longer warn by itself will report the following for each file:
```
cc1plus: warning: -Wabi won't warn about anything [-Wabi]
cc1plus: note: -Wabi warns about differences from the most up-to-date ABI, which is also used by default
cc1plus: note: use e.g. -Wabi=11 to warn about changes from GCC 7
```
add -Wundef since it is a useful warning
=>  updated CMake to include warnings and syntax check

simplecpp.cpp, test.cpp
Working with cppcheck I've faced off the issue in case using macros with octal numbers (access modes for files in UNIX). So I've create patch for simplecpp.cpp to fix this issue. The patch has been tested for a while in my own cppcheck build. I guess that it looks stable to be included in master.
=> Added octal numbers recognition

simplecpp.cpp, test.cpp
Using cppcheck -E to preprocess code with ellipsis produces output that
can't be compiled because ... is split into 3 tokens.
=> make ellipsis ... a single token

simplecpp.cpp
">> ==" was tokenized to ">>= =".  It is now tokenized to ">> ==".
=> Fix tokenization of ">> =="

simplecpp.cpp, test.cpp
Make simplecpp accept the following code:
const char*ptr="\\
\n";
Output from simplecpp:
const char * ptr = "\\n"
;
Output from gcc -E:
const char* ptr = "\\n";
Do this by extending the special casing for backslashes to read all
consecutive backslashes before continuing.
This makes it possible to run simplecpp on ftp://ftp.se.debian.org/debian/pool/main/l/lisaac/lisaac_0.39~rc1.orig.tar.gz
(used in cppcheck daca@home). Processing it is a blocker for cppcheck trac ticket [#2435](https://trac.cppcheck.net/ticket/2435).
Fixes #120.
=> Fix #120 (handle multiline character literals)

simplecpp.cpp, test.cpp
Handle plus and minus sign in the exponent. Hexadecimal floating point
numbers were added in C99 and C++17.
References:
https://en.cppreference.com/w/cpp/language/floating_literal
https://en.cppreference.com/w/c/language/floating_constant
I think this should be sufficient to close cppcheck trac ticket [#6514](https://trac.cppcheck.net/ticket/6514).
Related is [#8886](https://trac.cppcheck.net/ticket/8886), but that seems to be a design decision to warn about equality for floating point values.
=> Improve support for hexadecimal floating point literal

simplecpp.cpp, test.cpp
Most test cases are from https://en.cppreference.com/w/cpp/language/floating_literal
=> Fix hexadecimal float parsing when dot is followed by letter

main.cpp, simplecpp.cpp, simplecpp.h, test.cpp
If a file is explicitly included for example via command line option
`-include=` but can not be opened this error message is issued now.
Example:
$ ./simplecpp -include=blah.h foo.c
int main ( )
{
return 0 ;
}
foo.c:1: missing header: Can not open include file 'blah.h' that is explicitly included for all files.
Fixes #183
=> simplecpp.cpp: Issue error when an explicitly included file is not found

CMakeLists.txt, simplecpp.cpp, test.cpp
As an add-on the test running `testrunner` is added to the cmake test suite.  Please note that there is some more work to be done to `run-tests.py`, since for me this produces an error:
~~~python
$ python3 run-tests.py
Traceback (most recent call last):
File "run-tests.py", line 18, in <module>
for line in open(f, 'rt'):
File "C:/msys64/mingw64/lib/python3.8/encodings/cp1252.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 495: character maps to <undefined>
~~~   
@danmar Would you propagate the changes to `simplecpp.cpp` in the `cppcheck` repo?  I am not sure how you keep the files in sync if this is a goal.  But happy to submit the change to `simplecpp.cpp` in a `cppcheck` PR …
=> bug fix - de-escape double backslashes in file paths of #line directives

simplecpp.cpp
@danmar I just realized that for cppcheck files astyle configs are applied. Great I think if this patch is squashed onto fc32948 or applied separately - as you prefer, of course.
Thanks.
=> simplecpp.cpp: astyling

simplecpp.cpp
The local variable `altop` was shadowed by the global at https://github.com/danmar/simplecpp/blob/c27e5d46dced1f8ead1f3a755ce539cdd0ee42b2/simplecpp.cpp#L2241
=> Fixed -Wshadow warning.

run-tests.py
`python` is sometimes python 2 and sometimes python 3. Let's make the tests easy to run regardless.
=> run-tests: Make it run with both python 2 and 3

simplecpp.cpp, test.cpp
```
#define MAX_FOO (2 * 1)
#define MAX_FOO_AA (3 * 1)
#define M(UpperCaseName, b)                \
do {                                     \
int MaxValue = MAX_##UpperCaseName;    \
if (b) {                               \
MaxValue = MAX_##UpperCaseName##_AA; \
}                                      \
} while (0)
static void f(bool b) { M(FOO, b); }
```
was a preprocessor error
`a.cpp:4:0: error: failed to expand 'M', Invalid ## usage when expanding 'M'. [preprocessorErrorDirective]`
because `MAX_##UpperCaseName##_AA` was expanded to (2 * 1)##_AA, while gcc or clang happily expand it to `(3 * 1)`.
I don't really know how to add a test here (I've quickly tested with cppcheck and it seemed ok). I see there are some tests in cppcheck/test/testpreprocessor.cpp but I'm probably a bit …
=> Fix preprocessing of several ##

simplecpp.cpp, test.cpp
This fixes daca reports such as
```
tracetuner_3.0.6beta/src/mkchk/checkbcphd.c:0:0: error: Internal Error. MathLib::toLongNumber: characterLiteralToLL('\%') => invalid escape sequence [cppcheckError]
xview-3.2p1.4/util/xgettext/xgettext.c:0:0: error: Internal Error. MathLib::toLongNumber: characterLiteralToLL('\(') => invalid escape sequence [cppcheckError]
afterstep-devel-2.2.12/libAfterConf/Color.c:0:0: error: Internal Error. MathLib::toLongNumber: characterLiteralToLL('\{') => invalid escape sequence [cppcheckError]
NetworkManager-1.30.0/src/core/settings/plugins/ifcfg-rh/shvar.c:0:0: error: Internal Error. MathLib::toLongNumber: characterLiteralToLL('\E') => invalid escape sequence [cppcheckError]
```
which use extensions that are supported by both GCC and Clang.
This does not fix …
=> Support some more GCC extensions for character literals

simplecpp.cpp, test.cpp
This should resolve most daca reports of the following kinds:
```
head glibc-2.31/libio/tst-ftell-partial-wide.c:0:0: error: Internal Error. MathLib::toLongNumber: characterLiteralToLL(L'\343\201\224') => non-ASCII source characters supported only in narrow character literals [cppcheckError]
head foot-1.6.4/main.c:0:0: error: Internal Error. MathLib::toLongNumber: characterLiteralToLL(U'\303\266') => non-ASCII source characters supported only in narrow character literals [cppcheckError]
head icu/source/i18n/formatted_string_builder.cpp:0:0: error: Internal Error. MathLib::toLongNumber: characterLiteralToLL(u'') => non-ASCII source characters supported only in narrow character literals [cppcheckError]
```
by assuming that non-narrow literals are passed to `characterLiteralToLL` encoded in …
=> Basic support for UTF-8 source in character literals

simplecpp.cpp, test.cpp
Rejects overlong encodings and adds some more rejection test cases.
Does not handle noncharacters specifically. If the noncharacter code
points are going to be used for program-internal purposes, this decoder
needs to be updated to reject or replace them on incoming input.
=> Improve validation of UTF-8 encoded character literals

simplecpp.cpp, test.cpp
Only the last token in the argument token sequence substituted in front
of a ## should be concatenated. Previously the argument token sequence
was interpreted as a single token and concatenated.
Fixes #202.
=> Fix ## with multiple tokens in macro argument.

CMakeLists.txt, Makefile, simplecpp.cpp, simplecpp.h
This adds `nullptr` as a define when in c++03 mode allowing the code to be compiled against c++11 code without raising such warnings. AppleClang always defines it - even in c++03 mode.
=> fixed -Wzero-as-null-pointer-constant Clang warnings

simplecpp.cpp, simplecpp.h
`lastLine()` is only used to check for preprocessor directives. So if it isn't such there's no need to stringify it saving a lot of unnecessary `std::string` operations.
The intermediate increase comes from not constructing `std::string` objects on-the-fly for `std::string::insert()` and simply using the literals.
Testing with `-q -Ilib/ -D__GNUC__ lib/valueflow.cpp` this saves about 8% of total Ir.
Clang 13 `298,836,106` -> `295,950,055` -> `267,545,621`
GCC 11 `305,058,160` -> `299,749,788` -> `271,347,737`
=> only stringify the last line in `TokenList::readfile()` if necessary 

test.cpp
This is the first round of cleanups of redundant code end explicit usage of `std::istringstream` in the tests.
=> some testrunner cleanups

simplecpp.cpp, simplecpp.h, test.cpp
This exposes logic which is duplicated in Cppcheck.
Actually Cppcheck doesn't even need this logic (the code which uses this and was added by me was just the wrong approach) but that's a later cleanup within Cppcheck. And it still makes sense to have this functionality.
=> exposed -std to define mapping in interface / add support for more -std values / added setting of __STDC_VERSION__

run-tests.py, simplecpp.cpp, test.cpp
Building on the approach from PR https://github.com/danmar/simplecpp/pull/169 this special cases the `##` pasting in `expandHashHash` for string and character literals to allow for (user-defined) literals (`operator “”`).
- The string/char case is in it’s own `if` block; it’s not necessarily elegant but trying to maintain a single tokensB/strAB path through the other branches seems harder to follow (\*).
- There’s a dangling TODO because while ## ## or varargs combos appear to work, it’d be great if someone could review that assumption.
- Added some additional `hashhash` test cases. Suggestions for other/better boundary cases welcome.
- In at least two tests (`hashhash18`, `hashhash19`) the result of ## isn’t actually useful (and does eventually produce a syntax error in `cppcheck`). …
=> Special-case ## pasting to string/character constants (issue #168)

simplecpp.cpp, simplecpp.h
I had to use the Visual Studio IDE to build it to get these issues. They did not happen when using CMake. This could also indicate that the configuration of the CMake Visual Studio build does not match the existing VS project files. Something to look into when we get ready to drop the VS project files.
This removes the `static` specifiers I incorrectly added to some new function in the `simplecpp` name in a58ae6283b9b62ba694034576707c612c3cbce6b. I somehow assumed those are class members.
The issue with duplicated function definitions of `isStringLiteral` and `isCharLiteral` appears to be a compiler bug. There's functions of the same name in `utils.h` in the Cppcheck source. These functions can never see each other but somehow the compiler has a problem with it. See …
=> fixed Cppcheck compilation with MSBuild

simplecpp.cpp
So we at least handle the `-std` values properly and set the built-in `__cplusplus` define.
I forgot to include this in https://github.com/danmar/simplecpp/pull/242. This also still prevents https://github.com/danmar/cppcheck/pull/3212 from working.
=> support C++23 dialects for `-std` and updated some comments

test.cpp
This gets rid of all the explicit `std::istringstream` usage in the test cases so I can hopefully easily switch the implementation for the new API introduced with #244.
=> even more testrunner cleanups

simplecpp.cpp
Before:
```
simplecpp.cpp:2070:22: warning: padding class 'simplecpp::Macro' with 7 bytes to align 'valueToken' [-Wpadded]
simplecpp.cpp:1277:11: warning: padding size of 'simplecpp::Macro' with 7 bytes to alignment boundary [-Wpadded]
```
After:
```
simplecpp.cpp:1278:11: warning: padding size of 'simplecpp::Macro' with 6 bytes to alignment boundary [-Wpadded]
```
=> reduced padding in `simplecpp::Macro`

simplecpp.cpp
This reduces Ir in the proposed callgrind step in #4171 from `82,239,299,916` to `80,867,576,736` (some other optimizations were applied beforehand).
=> `TokenList` move constructor was also calling the copy constructor

simplecpp.cpp
I looks like a false positive but using a non-POD variable in a ternary causes it to be copied - see https://reviews.llvm.org/D137205#3939210.
Since simplecpp also supports pre-C++11 standards `std:move()` could not be used and I refactored the code instead getting rid of the ternaries.
=> avoid unnecessary copy in `openHeader()` - detected by upcoming clang-tidy check `performance-unnecessary-copy-on-last-use`

.github/workflows/CI-unixish.yml, .github/workflows/CI-windows.yml, .github/workflows/clang-tidy.yml
This updates the actions used in the workflows to address the following warning:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16
```
=> address deprecation warnings in GitHub workflows / fixed check for `libstdc++` debug mode step

.github/workflows/CI-unixish.yml
I followed the documentation from https://libcxx.llvm.org/DesignDocs/DebugMode.html#using-the-debug-mode which refers to `LIBCXX_ENABLE_DEBUG_MODE`. But that is a CMake define you are supposed to pass when building `libc++`. Also the debug mode needs the library to be built with it which is not something we do. So as suggested we should enable the assertions via `_LIBCPP_ENABLE_ASSERTIONS=1` instead - see https://libcxx.llvm.org/UsingLibcxx.html#assertions-mode.
=> CI-unixish.yml: specify proper define for "safe libc++"

simplecpp.cpp, test.cpp
Sometimes, `#include` directives with angle-bracket filespec delimiters are used (or abused) to defeat the preprocessor's behaviour where it tries to find a header file at a path relative to the file containing the directive.
Without this fix, any non-root header file, `foo/bar.h`, which does
```c
#include <bar.h>
```
while intending to include a root-level header file, will instead enter an infinite inclusion loop, terminating when the inclusion stack overflows with a `#include nested too deeply` error.
See also [this cppcheck issue](https://trac.cppcheck.net/ticket/7840).
=> Includes of system headers are never implicitly relative to the source file

simplecpp.cpp, simplecpp.h
This necessary for the missing include tests in Cppcheck to work. As well for contexts where this exists across multiple scans - this currently lacks proper support in Cppcheck though.
=> added `DUI::clearIncludeCache` to clear the non-existing files cache

simplecpp.cpp
This reduces the amount of Ir when scanning `ruby-lapack` by more than half.
=> optimized `simplifyPath()` a bit

CMakeLists.txt, simplecpp.h
Compiling with MSVC proves to be an unpleasant experience due to MSVC unreasonably complaining about the following:
It complains about this library using `fopen` instead of their CRT non-standard `fopen_s` function.
This warning cannot be suppressed by adding a definition to the `simplecpp.h` header, it does not work somehow. 
It is a bug I've always had with programs compiled with MSVC. I have always added `_CRT_SECURE_NO_WARNINGS` to the preached header but because this repository does not have one I have opted to add it to the CMAKE file.
Finally, the most annoying warnings are suppressed successfully using pragma directives.
Without these pragmas, my MSVC produces an immense build log full of warnings.
I hope this PR is appreciated in respect of: …
=> suppress msvc warnings about totally safe functions

simplecpp.cpp, test.cpp
Should hopefully also fix #297.
=> Do not confuse defines and designated initializers as float literals

simplecpp.h
Those were introduced by #298.
=> simplecpp.h: push and pop the MSVC warning disabling `#pragma` so they don't spill into user code

.clang-tidy
I still had this in a branch with the accompanied fixes. But there no longer is a warning so I guess I already fixed that in one of my previous commits.
=> .clang-tidy: enabled `performance-move-constructor-init`

simplecpp.cpp
The value for `__cplusplus` with C++23 is documented at [https://gcc.g…](https://gcc.gnu.org/onlinedocs/cpp/Standard-Predefined-Macros.html) 
…nu.org/onlinedocs/cpp/Standard-Predefined-Macros.html.
=> return proper `__cplusplus` value for C++23 / improved preliminary C23 support

simplecpp.cpp
calling `isspace()` is unnecessary since we handle all non-ASCII characters and already have special handling of all remaining whitespaces according to https://en.cppreference.com/w/cpp/string/byte/isspace.
Runinng with `-q -D__GNUC__ -Ilib lib/valueflow.cpp`
Clang 16 `276,826,655` -> `270,642,840`
GCC 13 `283,762,095`-> `280,179,302`
=> avoid some redundant checks in `TokenList::readfile()`

simplecpp.cpp, test.cpp
This change adds support for `__VA_OPT__` in variadic macros. This should close #191
=> Added support for `__VA_OPT__` expansion

simplecpp.cpp, simplecpp.h
Using the headers from https://sourceforge.net/p/cppcheck/discussion/development/thread/4e3ff7c875/:
a.h
```
Benchmark 1: ./simplecpp -q test.c
Time (mean ± σ):       9.2 ms ±   0.6 ms    [User: 8.1 ms, System: 1.2 ms]
Range (min … max):     8.3 ms …  11.4 ms    250 runs
```
```
Benchmark 1: ./simplecpp -q test.c
Time (mean ± σ):       3.4 ms ±   0.5 ms    [User: 2.6 ms, System: 1.2 ms]
Range (min … max):     2.3 ms …   5.8 ms    488 runs
```
b.h
```
Benchmark 1: ./simplecpp -q test.c
Time (mean ± σ):     140.6 ms ±   1.7 ms    [User: 137.2 ms, System: 3.3 ms]
Range (min … max):   137.6 ms … 143.8 ms    20 runs
```
```
Benchmark 1: ./simplecpp -q test.c
Time (mean ± σ):      13.2 ms ±   1.4 ms    [User: 10.4 ms, System: 2.8 ms]
Range (min … max):    11.7 ms …  19.3 ms    148 runs
```
=> optimized `lastLine()` usage in `readfile()`

simplecpp.cpp, test.cpp
```
/usr/bin/../include/c++/v1/vector:570:16: runtime error: reference binding to null pointer of type 'const value_type' (aka 'const simplecpp::Token *const')
#0 0x641340cb01e2 in front /usr/bin/../include/c++/v1/vector:570:9
#1 0x641340cb01e2 in simplecpp::Macro::expandToken(simplecpp::TokenList*, simplecpp::Location const&, simplecpp::Token const*, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, simplecpp::Macro, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, …
```
=> fixed fuzzing crash in `simplecpp::Macro::expandToken()`

main.cpp, simplecpp.cpp, simplecpp.h
The CLI application was pre-loading the included files just to remove the comments. Adding a `DUI` option for that makes it necessary. This makes profiling with the CLI more useful and it also fixes a potential memory leak in the CLI when an empty (or currently also non-existent) include was specified.
=> refs #342 - do not load included files twice in CLI application / added `DUI::removeComment`

simplecpp.cpp
`include-what-you-use` and `clang-include-cleaner` disagree about this. Since we have the latter enabled in this repo appease it for now by re-adding the include and suppress the IWYU warning.
=> mitigated `include-what-you-use` warnings

simplecpp.cpp
The check in `simplecpp::preprocess` obviously didn't work if `gnu++` or another alias were used. Also the simplification should only be performed if supported.
This does not fix the hang tracked in https://trac.cppcheck.net/ticket/11456. The code there is unfortunately a file which is over 1.5 MB big so we need to find a smaller sample.
=> improved prerequisite checks for `__has_include` handling

main.cpp, simplecpp.cpp, simplecpp.h, test.cpp
If the value is unknown we are silently setting an invalid/unexcepted value for the predefined macros which might lead to other issues.
=> refs #352 - generate output error on unknown `DUI::std` value

.github/workflows/CI-unixish.yml
`macos-11` is no longer available
=> CI-unixish.yml: removed `macos-11` / added `macos-13` and `macos-14`

.github/workflows/CI-unixish.yml, .github/workflows/CI-windows.yml, .github/workflows/clang-tidy.yml
see https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
=> updated GitHub actions to address Node 16 deprecation

CMakeLists.txt, run-tests.py, simplecpp.cpp, simplecpp.h, test.cpp
This fixes #31 as reproduced in TEST_CASE(define_define_11) without breaking code from @ydamigos's comment to #225 as reproduced in TEST_CASE(define_define_11a).  It thereby also fixes #293.
Subsequent commits in this PR address #66, #130, #241, #296.
=> Allow reexpansion of currently expanding macros during argument evaluation

simplecpp.cpp
I have the feeling that `isspace` is not portable. We include cctype.
=> replace 'isspace' with 'std::isspace'

simplecpp.cpp, test.cpp
When #pragma is a multiline directive, simplecpp doesn't mark the directive as a multiline resulting in a false positive of the end parenthesis ')'.
=> Multiline Pragma Directive False Positive

.github/workflows/CI-unixish.yml, .github/workflows/CI-windows.yml, .gitignore, integration_test.py, simplecpp.cpp, testutils.py
Fixes #402
This fix an issue of importing the same header by different addresses.
The issue is trickier than seems, because if a user used the include dir flag `-I...` with an absolute path, then every matched header was detected to be absolute, but if the import was a relative import to the source file and the source file isn't with an absolute path, than the header is identified by the combined relative path.
See https://sourceforge.net/p/cppcheck/discussion/general/thread/c01f80556b/
Note - I tried to make the code compatible with Windows, but was tested only on linux.
=> fix: use both absolute and relative header paths in header matching

simplecpp.cpp, simplecpp.h, test.cpp
=> Fix #404: simplecpp::TokenList::constFold does not fold '( 0 ) && 10 < X' properly

CMakeLists.txt
Fixes the following:
```
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.10 will be removed from a future version of
CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
```
=> bumped minimum CMake version to 3.10

simplecpp.cpp, simplecpp.h, test.cpp
This reverts commit aa3c4b6af92cbac5abf3c997f2e044db835e6cc6.
Got failures in Cppcheck CI when I bumped simplecpp, preprocessing is affected in a bad way.
=> Revert "Fix #404: simplecpp::TokenList::constFold does not fold '( 0 ) && 10 < X' properly (#405)"

.github/workflows/CI-windows.yml
`windows-2019` will be removed on June 30 and `windows-2025` is out of preview.
=> CI-windows.yml: removed `windows-2019` and added `windows-2025`

integration_test.py, simplecpp.cpp
fixes https://github.com/danmar/simplecpp/commit/07757314899f0a59d4bdb480015f21789a1db9be#commitcomment-156704346
cppcheck workflow checks: https://github.com/Tal500/cppcheck/pull/2
=> Preserve relativeness of included paths (w.r.t. current directory)

.github/workflows/CI-unixish.yml, .github/workflows/CI-windows.yml, integration_test.py, simplecpp.cpp
- Include also another integration test function to check header in parent dir usage (that was failing in previous commit).
- Add a safety check that we did not meet the header file that we are about to insert to the map (abort with stderr message otherwise) - this not only detect unmet bugs in including paths, but also avoid memory leak.
- Add much more cover in the test functions, and check more details.
=> fix: parent relative paths, and rework on the whole path extraction mechanics

integration_test.py, simplecpp.cpp
The specification from https://github.com/danmar/cppcheck/pull/7554#issuecomment-2933900683 :
A path (both for (1) top-level source files and (2) header files - i.e. files that are introduced by `#include`) will be absolute if and only if **at least** one of the condition is true:
1. The top-level source file (for headers it is the one that includes it) is given as an input file to simplecpp in its absolute form, **except** for the case that this is a header file that its inclusion was resolved by inclusion dirs (i.e. `-I`) - and this condition is false in that latter case (note that sometimes condition 3 can be true in that case, resulting in absolute flavor).
2. For header files only that are not system includes(i.e. `#include "..."`): The include path is absolute.
3. For header files …
=> change the rules of relativeness preserving to depend on the source file including it for relative path includes

simplecpp.cpp, test.cpp, testsuite/clang-preprocessor-tests/macro_fn_va_opt.c
Fixes `__VA_OPT__` by expanding it first, before further recursive expansions in variadic macros.
When a variadic macro containing a `__VA_OPT__` token is parsed, the macro is split into a different token list for the two possible cases, where each occurence of `__VA_OPT__` is either expanded and discarded. The correct token list is selected during macro expansion by examining the number of arguments, this way most of the extra processing required is only done once during the macro parsing, and only for variadic macros containing `__VA_OPT__`.
=> Fix #368 (__VA_OPT__ is not handled good enough)

.github/workflows/CI-unixish.yml
it will now actually bail out on errors
=> fixed #466 - CI-unixish.yml: added missing `UBSAN_OPTIONS`

.github/workflows/CI-unixish.yml, Makefile
Currently it was necessary to duplicate (and keep in sync) all the built-in flags if you just wanted to extend it. This introduced additional variables to make this easier.
=> Makefile: added `CXXOPTS` and `LDOPTS` to extend `CXXFLAGS` and `LDFLAGS`

simplecpp.cpp, simplecpp.h, test.cpp
Fix infinite loop in `simplecpp::load` with circular includes by removing scans of cached files.
=> Fix infinite loop with circular includes

.git-blame-ignore-revs
This file lists revisions that should be ignored when considering attribution for the actual code written. Code style changes should not be considered as modifications with regards to attribution.
To see clean and meaningful blame information.
```
$ git blame important.py --ignore-revs-file .git-blame-ignore-revs
```
To configure git to automatically ignore revisions listed in a file on every call to git blame.
```
$ git config blame.ignoreRevsFile .git-blame-ignore-revs
```
> [!TIP]
> `.git-blame-ignore-revs` is automatically detected by GitHub.
> See https://docs.github.com/en/repositories/working-with-files/using-files/viewing-and-understanding-files#ignore-commits-in-the-blame-view
>
---
Follow-up on the following pull requests:
* https://github.com/danmar/simplecpp/pull/517
* …
=> chore: Improve attribution by ignoring bulk formatting

.github/workflows/CI-unixish.yml, CMakeLists.txt, Makefile, test.cpp
This pull request fixes the execution of the `testrunner` in out-of-source builds by setting the `SIMPLECPP_SOURCE_DIR` definition. This change ensures that the test runner can correctly find include paths by using the source directory.
The `CMakeLists.txt` file is updated to define `SIMPLECPP_SOURCE_DIR`, and the test cases in `test.cpp` are modified to conditionally add this directory to the include paths if 
defined.
=> tests: Fix execution of testrunner for out-of-source builds

simplecpp.cpp, simplecpp.h, test.cpp
This is implemented in Cppcheck and simplecpp but their behavior differs. So this places a single (and improved) implementation in simplecpp for both to use.
=> improved and exposed `isAbsolutePath()`
