- simplecpp.cpp
Simplecpp does not support the "#line directive". This pull request fixes the problem.
> Support of #line directive

- main.cpp
test.cpp cannot be built as well.
> Refactor code to build with VS2010

- simplecpp.cpp
Part of Cppcheck PR https://github.com/danmar/cppcheck/pull/907
> ENH: perfomance: remove unused object

- simplecpp.cpp
- simplecpp.h
> Fix build with clang + small refactoring

- simplecpp.cpp
this fixes issue #85 and helps with the testproblem in cppcheck. simplecpp bump in cppcheck required.
> dont autocapitalize windows drive letters

- simplecpp.cpp
- declaration of 'files' hides class member
> Fix Visual Studio Warning C4458

- simplecpp.cpp
- simplecpp.h
This adds support for constant folding of the shift operators.
> Handle constant folding for the shift operators

- simplecpp.cpp
This replaces the mutex used by Scoped lock by a critical section.
The critical section is faster because it is process-local.
It reduces Cppcheck runtime from 42 mins to 31 mins (-26.2%, using -j24) on my large solution (see PR #144).
The performance gain will become even greater with caching extensions yet to come (in future PRs).
> use critical section in ScopedLock

- simplecpp.cpp
- simplecpp.h
I chose the random package `nn` for profiling.
> a few optimizations

- simplecpp.cpp
Thanks, I forked your repository.
> Use std::make_pair for simplicity

- run-tests.py
> Remove fixed test case from TODO

- .github/workflows/CI-unixish.yml
Inspired by https://github.com/danmar/simplecpp/pull/196#discussion_r532908189
> Add Valgrind to CI build

- .github/workflows/CI-unixish.yml
See https://github.com/danmar/simplecpp/pull/205#issuecomment-760310552 and https://github.com/danmar/cppcheck/commit/76d5e6c7dba4805e63a91508b863d5d935a3ec42
> Skip macos 11 for now

- simplecpp.cpp
> removed unused include

- simplecpp.cpp
This should be done even if such macros might only be defined further ahead.
Specifically, to mark include guard macros as used.
This fixes misra rule 2.5 false positives for the misra cppcheck addon
reported in cppcheck trac ticket #10751.
> consider cpp conditional expression tokens for macro usage

- simplecpp.cpp
- test.cpp
See https://gcc.gnu.org/onlinedocs/cpp/Standard-Predefined-Macros.html.
> added support for built-in defines __DATE__ and __TIME__

- simplecpp.cpp
- test.cpp
As has been suggested it would be useful to see _why_ a use of ## might be invalid. This covers the existing simple cases at least; anything deeper seems to require checking (re-tokenizing?) after `expandArg`/concatenation.
- I’ve left the base message as-is (might be slightly over-engineered). A minor niggle might be that the macro name is included twice in the resulting output?
- The distinction between `unexpectedToken` and `cannotCombine` is somewhat arbitrary.
> Show more details for invalid ## usage

- simplecpp.cpp
- test.cpp
This PR is, pretty much, #245 with conflict resolution and tests.
The original fix by @ceggers-arri seems perfectly fine: it passes whatever tests I came up with and fixes the problem I had with cppcheck (angle brackets).
> Improve support for __has_include

- simplecpp.cpp
Testing with `-q -Ilib/ -D__GNUC__ lib/valueflow.cpp`:
Clang 14 `271,886,478` -> `259,691,836`
GCC 12 `275,880,976` -> `262,961,857`
Testing with `-q -Ilib/ -D__GNUC__ lib/tokenize.cpp`:
Clang 14 `252,880,452` -> `241,542,054`
GCC 12 `257,203,604` -> `245,222,755`
> optimized `TokenList::readfile()` a bit

- simplecpp.cpp
- test.cpp
> Fix #344 fuzzing crash in simplecpp::preprocess()

- Makefile
this will execute the integration test with the sanitizers and hardening in the CI.
> fixed #464 - added integration test to `test` make target
